language: julia

os:
  - linux

julia:
  - nightly

matrix:
  allow_failures:
    - julia: nightly

## uncomment the following lines to override the default test script
script:
 - julia test/CircuitParserTest.jl